version: '3'
services:
  thingspeak:
    container_name: thingspeak
    image: synomi/thingspeak
    ports:
      - '8087:80'
    networks:
      - speak_net
  mysql:
    container_name: mysql55
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    image: mysql:5.5
    environment:
      - "MYSQL_ROOT_PASSWORD=speak"
    networks:
      - speak_net
networks:
    speak_net: